### ISSUE TITLE
Inverted logic for resolving tmpfs mounts?

### ISSUE THREAD

**Issue by tv42** [mgoltzsche/ctnr#4]
Hi. This looks wrong:

https://github.com/mgoltzsche/ctnr/blob/d3c30723cbaf48831ef9dcdeb12d63e6a5bb0ad1/model/resolve.go#L44-L45

```go
	if m.Source == "" && m.Type != MOUNT_TYPE_TMPFS {
		src = self.anonymous(m.Target)
```

I would have expected tmpfs to specifically want anonymous mount sources (`==` instead of `!=`).

Currently I have a `ctnr  run --mount type=tmpfs,dst=/foo` failing with

```
WARN[0000] exit status 1                                
ERRO[0000] run process: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/home/tv\\\" to rootfs \\\"/home/tv/.ctnr/bundles/p2jen2rvarc43inrum66qzktna/rootfs\\\" at \\\"/foo\\\" caused \\\"invalid argument\\\"\"" 
```

And it really doesn't seem like a tmpfs should be trying to mount my home dir.

Then again, `ctnr run --mount type=tmpfs,src=/tmp,dst=/foo` shows my host `/tmp` inside the container, so it seems that tmpfs mounts don't work at all.

**Comment by mgoltzsche** [comment]
Oups, I haven't seen this, sorry. Fixed in [v0.7.1-alpha](https://github.com/mgoltzsche/ctnr/releases/tag/v0.7.1-alpha) - although, to simply make the option work, it just bind mounts a directory within the bundle.
However I am not maintaining this project anymore in favour of [podman](https://github.com/containers/libpod) - I've added a note to the readme now.

**Comment by mgoltzsche** [comment]
UPDATE: looking at it again I realized it didn't fix it - sorry.

**Comment by tv42** [comment]
Thanks for fixing it. The deprecation is a little sad, libpod's dependencies are just beyond silly, Glib for a Go project...
